# Generated by Django 5.0.6 on 2024-07-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='name',
        ),
    ]
